services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "4040"
    environment:
      - PORT=4040
      - JWT_SECRET_KEY=...
      - MONGO_URL=mongodb://mongo:27017/testdb
    depends_on:
      - mongo
    networks:
      - internal-net

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    networks:
      - internal-net

  nginx:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - backend
    networks:
      - internal-net

volumes:
  mongo-data:

networks:
  internal-net:
    driver: bridge
